services:
  - type: web
    name: sahaba-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: RENDER_URL
        sync: false
      - key: GEMINI_KEY_1
        sync: false